# SUN8IW8 I3 Platform Support
snd-soc-v3-adcdac-objs := v3-adcdac.o

obj-$(CONFIG_SND_SOC_V3_CODEC) += snd-soc-v3-adcdac.o

snd-soc-v3-pcm-objs := v3-pcm.o

obj-$(CONFIG_SND_V3_SOC) += snd-soc-v3-pcm.o



# SUN8IW8 I3 Machine Support
snd-soc-v3-codec-objs := v3-codec.o

obj-$(CONFIG_SND_SOC_V3_CODEC) += snd-soc-v3-codec.o


snd-soc-v3-audio-objs := v3-audio.o

obj-$(CONFIG_SND_V3_SOC) += snd-soc-v3-audio.o

